### ISSUE TITLE
it does segfault on rpi4 (retest)

### ISSUE THREAD

**Issue by Askmewho** [civctp2/civctp2#262]
```
pi@raspberrypi:~/ctp2/ctp2_program/ctp $ gdb ./ctp2 
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./ctp2...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/pi/ctp2/ctp2_program/ctp/ctp2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb48351f0 (LWP 20205)]
[New Thread 0xb3bba1f0 (LWP 20206)]
[New Thread 0xb329b1f0 (LWP 20207)]
[New Thread 0xb19151f0 (LWP 20214)]
[New Thread 0xb11141f0 (LWP 20215)]
Detected Ogg Music track, using that instead of CD Audio
ui/aui_common/aui_movie.cpp L640: SDL mouse code is missing here!

Thread 1 "ctp2" received signal SIGSEGV, Segmentation fault.
0x00265cf0 in spnewgametribescreen_addAllTribes() ()
(gdb) bt
#0  0x00265cf0 in spnewgametribescreen_addAllTribes() ()
#1  0x00265ca0 in spnewgametribescreen_addAllTribes() ()
#2  0x00264f88 in spnewgametribescreen_Initialize(void (*)(aui_Control*, unsigned int, unsigned int, void*)) ()
#3  0x002620ac in spnewgamescreen_displayMyWindow() ()
#4  0x00214ddc in initialplayscreen_newgamePress(aui_Control*, unsigned int, unsigned int, void*) ()
#5  0x000965f0 in aui_Button::MouseLDropInside(aui_MouseEvent*) ()
#6  0x00191c30 in ctp2_Button::MouseLDropInside(aui_MouseEvent*) ()
#7  0x000da0c4 in aui_Region::MouseDispatch(aui_MouseEvent*, unsigned int) ()
#8  0x000d2eb0 in aui_Region::HandleMouseEvent(aui_MouseEvent*, unsigned int)
    ()
#9  0x000d2d7c in aui_Region::HandleMouseEvent(aui_MouseEvent*, unsigned int)
    ()
#10 0x000f3ee8 in aui_UI::HandleMouseEvents(int, aui_MouseEvent*) ()
#11 0x000f45fc in aui_UI::Process() ()
#12 0x0002047c in CivApp::ProcessUI(unsigned int, unsigned int&) ()
#13 0x00020b10 in CivApp::Process() ()
#14 0x00015f60 in CivMain(int, char**) ()
#15 0x00015a04 in main ()
```

**Comment by LynxAbraxas** [comment]
@Askmewho Do the hints of #277 (deleting LDLs and renaming (as long as #276 is not merged)) solve your segfault?

**Comment by MartinGuehmann** [comment]
It is clearly the same stack trace that's why I linked it.

**Comment by LynxAbraxas** [comment]
> It is clearly the same stack trace that's why I linked it.

Definitely, well spotted, just commented because the linking does not ping @Askmewho and it would be good to know if it works for @Askmewho.

**Comment by Askmewho** [comment]
I will test that soon

**Comment by Askmewho** [comment]
solved after rm ~/ctp/ctp2_data/english/uidata/layouts/*

**Comment by LynxAbraxas** [comment]
Cool, thanks @Askmewho for reporting back. So happy playing, and let us know if you stumble on any other issues.

**Comment by Askmewho** [comment]
@LynxAbraxas So far, it seems it runs ok. It doesnt use opengl (it seems) 
https://youtu.be/V-mPbaeKN1Q

Sorry for the gameplay... Its quite different than the civilization 2 I played on the 90s hahhahs

**Comment by LynxAbraxas** [comment]
Looks good, the unit animation seems to get stuck sometimes, or is that a side effect of the screen casting? What happens if you turn on good animation?

**Comment by Askmewho** [comment]
Yeah, the animations are not working properly. I will retest that soon. But its playable even at 1080p
